---
- hosts: localhost
  connection: local
  tasks:
    - name: Install postgres dev files
      apt: name=libpq-dev
      sudo: yes
  roles:
  - role: common
  - role: alban.andrieu.dropbox
  - role: ThePixelDeveloper.google-chrome
  - role: ANXS.postgresql
    sudo: yes
    postgresql_version: 9.1
    postgresql_locale: 'nl_BE.UTF-8'
    postgresql_apt_repository: 'deb http://apt.postgresql.org/pub/repos/apt/ utopic-pgdg main'
    postgresql_databases:
      - name: budgetapp
    postgresql_users:
      - name: budgetapp
        pass: budgetapp
        encrypted: no
      - name: ecto
        pass: ecto
        encrypted: no
    postgresql_user_privileges:
      - name: budgetapp
        db: budgetapp
        priv: 'ALL'
        role_attr_flags: 'SUPERUSER'
      - name: ecto
        role_attr_flags: 'SUPERUSER'
