---
- hosts: localhost
  connection: local
  roles:
  - role: common
  - role: rvm_io.rvm1-ruby
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_user_id }}/.rvm'
    rvm1_user: '{{ ansible_user_id }}'
  - role: alban.andrieu.dropbox
  - role: ThePixelDeveloper.google-chrome
  - role: smola.java
    sudo: yes
    java_packages:
      - oracle-java7-installer
  - role: ANXS.postgresql
    sudo: yes
    postgresql_version: 9.4
    postgresql_databases:
      - name: tradelec
        uuid_ossp: yes
      - name: test
        uuid_ossp: yes
    postgresql_users:
      - name: intouchbase
        pass: intouchbase
        encrypted: no
    postgresql_user_privileges:
      - name: intouchbase
        db: tradelec
        priv: "ALL"
        role_attr_flags: "SUPERUSER"
      - name: intouchbase
        db: test
        priv: "ALL"
        role_attr_flags: "SUPERUSER"
