---
- hosts: localhost
  connection: local
  roles:
  - role: common
  - role: rvm_io.rvm1-ruby
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_user_id }}/.rvm'
    rvm1_user: '{{ ansible_user_id }}'
  - role: alban.andrieu.dropbox
  - role: ThePixelDeveloper.google-chrome
  - role: smola.java
    sudo: yes
    java_packages:
      - oracle-java7-installer
  - role: intellij
    sudo: yes
  - role: ANXS.postgresql
    sudo: yes
    postgresql_version: 9.1
    postgresql_locale: 'nl_BE.UTF-8'
    postgresql_apt_repository: 'deb http://apt.postgresql.org/pub/repos/apt/ utopic-pgdg main'
