---
- hosts: localhost
  connection: local
  tasks:
    - name: Install postgres dev files
      apt: name=libpq-dev
      sudo: yes
  roles:
  - role: common
  - role: hipchat
  - role: rvm_io.rvm1-ruby
    rvm1_install_flags: '--auto-dotfiles --user-install --with-gems="bundler tmuxinator guard vimdeck"'
    rvm1_install_path: '/home/{{ ansible_user_id }}/.rvm'
    rvm1_user: '{{ ansible_user_id }}'
  - role: elixir
  - role: alban.andrieu.dropbox
  - role: ThePixelDeveloper.google-chrome
  - role: smola.java
    sudo: yes
    java_packages:
      - oracle-java7-installer
  - role: intellij
    sudo: yes
  - role: azavea.vagrant
    vagrant_version: "1.7.4"
    sudo: yes
  - role: ANXS.postgresql
    sudo: yes
    postgresql_version: 9.1
    postgresql_locale: 'nl_BE.UTF-8'
    postgresql_apt_repository: 'deb http://apt.postgresql.org/pub/repos/apt/ utopic-pgdg main'
    postgresql_databases:
      - name: budgetapp
      - name: test
        uuid_ossp: yes
    postgresql_users:
      - name: intouchbase
        pass: intouchbase
        encrypted: no
      - name: budgetapp
        pass: budgetapp
        encrypted: no
      - name: tradelec_tenant
        pass: tradelec_tenant
        encrypted: no
      - name: ecto
        pass: ecto
        encrypted: no
    postgresql_user_privileges:
      - name: intouchbase
        db: test
        priv: 'ALL'
        role_attr_flags: 'SUPERUSER'
      - name: budgetapp
        db: budgetapp
        priv: 'ALL'
        role_attr_flags: 'SUPERUSER'
      - name: tradelec_tenant
        db: test
        priv: 'ALL'
        role_attr_flags: 'SUPERUSER'
      - name: ecto
        role_attr_flags: 'SUPERUSER'
