---
- hosts: localhost
  connection: local
  vars:
    body:
      title: "Laptop"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  vars_prompt:
    - name: user_name
      prompt: "What is your user name for github?"
      private: no
    - name: password
      prompt: "What is your password for github?"
      private: yes
  tasks:
    - name: Install public key
      uri: >
        dest=~/.ssh/github
        creates=~/.ssh/github
        method=POST
        status_code=201
        url=https://api.github.com/user/keys
        user={{ user_name }}
        password={{ password }}
        force_basic_auth=yes
        body='{{ body | to_json }}'
        body_format=json
