---
- name: Download erlang package
  get_url: dest=/tmp url=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
- name: Install erlang package
  apt: deb=/tmp/erlang-solutions_1.0_all.deb state=present
  sudo: yes
- name: Install elixir
  apt: name=elixir update_cache=yes state=present
  sudo: yes
- name: Install erlang-dev
  apt: name=erlang-dev state=present
  sudo: yes
- name: Install erlang-base-hipe
  apt: name=erlang-base-hipe
  sudo: yes
- name: Install erlang-eunit
  apt: name=erlang-eunit
  sudo: yes
- name: Install erlang-parsetools
  apt: name=erlang-parsetools
  sudo: yes
